import 'package:flutter/material.dart';
import 'package:task_manager/main.dart';
import 'package:task_manager/models/database_helper.dart';
import 'package:task_manager/models/task.dart';

class UpdateorDeleteTask extends StatefulWidget { final int index; const UpdateorDeleteTask({super.key, required this.index}); @override State<UpdateorDeleteTask> createState() => _UpdateorDeleteTaskState(); }
class _UpdateorDeleteTaskState extends State<UpdateorDeleteTask> { late final TextEditingController _title; late final TextEditingController _date; String? _priority; final _priorities = ['High', 'Medium', 'Low']; late Task _task;
  @override void initState() { super.initState(); final row = tasks[widget.index]; _task = Task(id: row[0] as int, title: row[1] as String, date: row[2] as String, level: row[3] as String, completed: row[4] as bool); _title = TextEditingController(text: _task.title); _date = TextEditingController(text: _task.date); _priority = _task.level; }
  Future<void> _selectDate() async { final picked = await showDatePicker(context: context, initialDate: DateTime.now(), firstDate: DateTime(2000), lastDate: DateTime(2100)); if (picked != null) setState(() => _date.text = '${picked.day.toString().padLeft(2, '0')}.${picked.month.toString().padLeft(2, '0')}.${picked.year}'); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Update Task')), body: Padding(padding: const EdgeInsets.all(24), child: Column(children: [TextField(controller: _title, decoration: const InputDecoration(labelText: 'Title')), const SizedBox(height: 16), TextField(controller: _date, readOnly: true, onTap: _selectDate, decoration: const InputDecoration(labelText: 'Date', suffixIcon: Icon(Icons.calendar_today))), const SizedBox(height: 16), DropdownButtonFormField<String>(value: _priority, decoration: const InputDecoration(labelText: 'Priority'), items: _priorities.map((p) => DropdownMenuItem(value: p, child: Text(p))).toList(), onChanged: (value) => setState(() => _priority = value)), const SizedBox(height: 24), SizedBox(width: double.infinity, child: FilledButton(onPressed: () async { await DatabaseHelper().updateTask(Task(id: _task.id, title: _title.text.trim(), date: _date.text, level: _priority ?? _task.level, completed: _task.completed)); if (mounted) Navigator.pop(context); }, child: const Text('Update'))), const SizedBox(height: 12), SizedBox(width: double.infinity, child: OutlinedButton(onPressed: () async { await DatabaseHelper().deleteTask(_task.id!); if (mounted) Navigator.pop(context); }, child: const Text('Delete')))])));
  @override void dispose() { _title.dispose(); _date.dispose(); super.dispose(); }
}
