import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/task.dart';
import '../providers/auth_provider.dart';
import '../providers/task_provider.dart';
import '../providers/theme_provider.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  String _filter = 'All';
  @override Widget build(BuildContext context) { final provider = context.watch<TaskProvider>(); final visible = provider.tasks.where((task) => _filter == 'All' || (_filter == 'Active' && !task.completed) || (_filter == 'Completed' && task.completed)).toList(); return Scaffold(appBar: AppBar(title: const Text('My Tasks')), drawer: _drawer(context), body: Column(children: [Padding(padding: const EdgeInsets.all(16), child: SegmentedButton<String>(segments: const [ButtonSegment(value: 'All', label: Text('All')), ButtonSegment(value: 'Active', label: Text('Active')), ButtonSegment(value: 'Completed', label: Text('Done'))], selected: {_filter}, onSelectionChanged: (selection) => setState(() => _filter = selection.first))), Expanded(child: provider.error != null ? Center(child: Text(provider.error!)) : visible.isEmpty ? const Center(child: Text('No tasks yet. Tap + to add one.')) : ListView.builder(padding: const EdgeInsets.symmetric(horizontal: 16), itemCount: visible.length, itemBuilder: (_, index) => _TaskTile(task: visible[index], onEdit: () => _showForm(context, visible[index]))))]), floatingActionButton: FloatingActionButton.extended(onPressed: () => _showForm(context), icon: const Icon(Icons.add), label: const Text('New task'))); }
  Widget _drawer(BuildContext context) => Drawer(child: SafeArea(child: Column(children: [ListTile(leading: const Icon(Icons.account_circle), title: Text(context.read<AuthProvider>().user?.email ?? 'Account')), Consumer<ThemeProvider>(builder: (_, theme, __) => SwitchListTile(title: const Text('Dark mode'), value: theme.mode == ThemeMode.dark, onChanged: (_) => theme.toggle())), const Spacer(), ListTile(leading: const Icon(Icons.logout), title: const Text('Sign out'), onTap: () => context.read<AuthProvider>().signOut())])));
  Future<void> _showForm(BuildContext context, [Task? task]) async { final title = TextEditingController(text: task?.title); final description = TextEditingController(text: task?.description); final key = GlobalKey<FormState>(); await showDialog<void>(context: context, builder: (_) => AlertDialog(title: Text(task == null ? 'New task' : 'Edit task'), content: Form(key: key, child: Column(mainAxisSize: MainAxisSize.min, children: [TextFormField(controller: title, autofocus: true, decoration: const InputDecoration(labelText: 'Title'), validator: (value) => value == null || value.trim().isEmpty ? 'Enter a title' : null), const SizedBox(height: 12), TextField(controller: description, maxLines: 3, decoration: const InputDecoration(labelText: 'Description (optional)'))])), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () { if (!key.currentState!.validate()) return; final tasks = context.read<TaskProvider>(); if (task == null) { tasks.add(title.text, description.text); } else { tasks.update(task, title.text, description.text); } Navigator.pop(context); }, child: const Text('Save'))])); title.dispose(); description.dispose(); }
}
class _TaskTile extends StatelessWidget { const _TaskTile({required this.task, required this.onEdit}); final Task task; final VoidCallback onEdit; @override Widget build(BuildContext context) => Dismissible(key: ValueKey(task.id), direction: DismissDirection.endToStart, background: Container(color: Colors.red, alignment: Alignment.centerRight, padding: const EdgeInsets.only(right: 20), child: const Icon(Icons.delete, color: Colors.white)), confirmDismiss: (_) => _confirm(context), onDismissed: (_) => context.read<TaskProvider>().remove(task), child: Card(margin: const EdgeInsets.only(bottom: 8), child: ListTile(onTap: onEdit, leading: Checkbox(value: task.completed, onChanged: (_) => context.read<TaskProvider>().toggle(task)), title: Text(task.title, style: TextStyle(decoration: task.completed ? TextDecoration.lineThrough : null, fontWeight: FontWeight.w600)), subtitle: task.description.isEmpty ? null : Text(task.description, maxLines: 2, overflow: TextOverflow.ellipsis)))); }
  Future<bool> _confirm(BuildContext context) async => await showDialog<bool>(context: context, builder: (_) => AlertDialog(title: const Text('Delete task?'), content: const Text('This task will be deleted permanently.'), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Cancel')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('Delete'))])) ?? false;
}
